log_interval: 300
timeout: 5
console: no
store: yes
path: "./data/"
sync: yes
sync_path: "aws:~/dev/sensai/data"
alert: yes
alert_co2: 800

devices:
  - BA200.3: e7:d1:86:7e:ca:ce
  - Caldera: d6:77:32:ce:81:7a
