channels:
  - conda-forge
name: sensai
dependencies:
  - bokeh
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3
  - scipy
  - pip:
      - dash
      - bleak
      - gunicorn
      - influxdb-client
